src/Entity/Property.php
<?php

namespace App\Entity;

use Doctrine\ORM\Mapping as ORM;
use Cocur\Slugify\Slugify;
use Symfony\Component\Validator\Constraints as Assert;
use Symfony\Bridge\Doctrine\Validator\Constraints\UniqueEntity;

/**
 * @ORM\Entity(repositoryClass="App\Repository\PropertyRepository")
 * @UniqueEntity("title")
 */
class Property
{
    const Heat = [
        '1' => 'Electrique',
       '2' => 'Gaz'
    ];
    /**
     * @ORM\Id()
     * @ORM\GeneratedValue()
     * @ORM\Column(type="integer")
     */
    private $id;

    /**
     * @ORM\Column(type="string", length=255)
     * @Assert\Length(min=5, max=255)
     */
    private $title;

    /**
     * @ORM\Column(type="text", nullable=true)
     */
    private $description;

    /**
     * @ORM\Column(type="integer")
     *  @Assert\Range(min = 18, max = 400)
     */
    private $surface;

    /**
     * @ORM\Column(type="integer")
     */
    private $rooms;

    /**
     * @ORM\Column(type="integer")
     */
    private $bedrooms;

    /**
     * @ORM\Column(type="integer")
     */
    private $floor;

    /**
     * @ORM\Column(type="integer")
     */
    private $price;

    /**
     * @ORM\Column(type="integer")
     */
    private $heat;

    /**
     * @ORM\Column(type="string", length=255)
     */
    private $city;

    /**
     * @ORM\Column(type="string", length=255)
     *  @Assert\Regex("/^[0-9]{4}$/")
     */
    private $postal_code;

    /**
     * @ORM\Column(type="boolean", options={"default":false})
     */
    private $sold = false;

    /**
     * @ORM\Column(type="datetime")
     */
    private $created_at;

    /**
     * @ORM\Column(type="string", length=255)
     */
    private $adresse;

    public function __construct(){
        $this->created_at = new \Datetime();
    }

    public function getId(): ?int
    {
        return $this->id;
    }

    public function getTitle(): ?string
    {
        return $this->title;
    }

    public function setTitle(string $title): self
    {
        $this->title = $title;

        return $this;
    }

    public function getSlug(): string
    {
        return (new Slugify())->slugify($this->title);
    }

    public function getDescription(): ?string
    {
        return $this->description;
    }

    public function setDescription(?string $description): self
    {
        $this->description = $description;

        return $this;
    }

    public function getSurface(): ?int
    {
        return $this->surface;
    }

    public function setSurface(int $surface): self
    {
        $this->surface = $surface;

        return $this;
    }

    public function getRooms(): ?int
    {
        return $this->rooms;
    }

    public function setRooms(int $rooms): self
    {
        $this->rooms = $rooms;

        return $this;
    }

    public function getBedrooms(): ?int
    {
        return $this->bedrooms;
    }

    public function setBedrooms(int $bedrooms): self
    {
        $this->bedrooms = $bedrooms;

        return $this;
    }

    public function getFloor(): ?int
    {
        return $this->floor;
    }

    public function setFloor(int $floor): self
    {
        $this->floor = $floor;

        return $this;
    }

    public function getPrice(): ?int
    {
        return $this->price;
    }

    public function setPrice(int $price): self
    {
        $this->price = $price;

        return $this;
    }

    public function getHeat(): ?int
    {
        return $this->heat;
    }

    public function setHeat(int $heat): self
    {
        $this->heat = $heat;

        return $this;
    }

    public function HeatType(): string
    {
        return self::Heat[$this->heat];
    }

    public function getCity(): ?string
    {
        return $this->city;
    }

    public function setCity(string $city): self
    {
        $this->city = $city;

        return $this;
    }

    public function getPostalCode(): ?string
    {
        return $this->postal_code;
    }

    public function setPostalCode(string $postal_code): self
    {
        $this->postal_code = $postal_code;

        return $this;
    }

    public function getSold(): ?bool
    {
        return $this->sold;
    }

    public function setSold(bool $sold): self
    {
        $this->sold = $sold;

        return $this;
    }

    public function getCreatedAt(): ?\DateTimeInterface
    {
        return $this->created_at;
    }

    public function setCreatedAt(\DateTimeInterface $created_at): self
    {
        $this->created_at = $created_at;

        return $this;
    }

    public function getAdresse(): ?string
    {
        return $this->adresse;
    }

    public function setAdresse(string $adresse): self
    {
        $this->adresse = $adresse;

        return $this;
    }
}

src/Form/PropertyType.php
<?php

namespace App\Form;

use App\Entity\Property;
use Symfony\Component\Form\AbstractType;
use Symfony\Component\Form\FormBuilderInterface;
use Symfony\Component\OptionsResolver\OptionsResolver;
use Symfony\Component\Form\Extension\Core\Type\ChoiceType;

class PropertyType extends AbstractType
{
    public function buildForm(FormBuilderInterface $builder, array $options)
    {
        $builder
            ->add('title')
            ->add('description')
            ->add('surface')
            ->add('rooms')
            ->add('bedrooms')
            ->add('floor')
            ->add('price')
            ->add('heat',ChoiceType::class,[
                'choices' => $this->getchoices()
            ])
            ->add('city')
            ->add('postal_code')
            ->add('sold')
            ->add('adresse')
        ;
    }

    public function configureOptions(OptionsResolver $resolver)
    {
        $resolver->setDefaults([
            'data_class' => Property::class,
            'translation_domain' => 'forms'

        ]);
    }
    public function getchoices()
    {
        $choices = Property::Heat;
        $output= [];
        foreach($choices as $k => $v){
            $output[$v] = $k;
        }
        return $output;
    }
}

src/Controller/PropertyController.php
<?php 

namespace App\Controller;

use Symfony\Component\HttpFoundation\Response;
use Symfony\Component\Routing\Annotation\Route;
use Symfony\Component\HttpFoundation\Request;
use Symfony\Bundle\FrameworkBundle\Controller\AbstractController;
use Symfony\Component\HttpFoundation\RedirectResponse;
use Knp\Component\Pager\PaginatorInterface;
use Doctrine\ORM\EntityManagerInterface;
use App\Repository\PropertyRepository;
use App\Entity\Property;
use App\Entity\PropertySearch;
use App\Form\PropertySearchType;

class PropertyController extends AbstractController {

    /**
     * @var PropertyRepository
     */
    private $repository;

    /**
     * @var EntityManager
     */
    private $em;

    public function __construct(PropertyRepository $repository,EntityManagerInterface $em)
    {
        $this->repository = $repository;
        $this->em = $em;
    }

    public function index(PaginatorInterface $paginator, Request $request): Response
    {
       $search = new PropertySearch();
       $form = $this->createForm(PropertySearchType::class, $search);
       $form->handleRequest($request);

        $properties =$paginator->paginate(
            $this->repository->findAllVisibleQuery($search), /* query NOT result */
            $request->query->getInt('page', 1),
            12
        );
        return $this->render('property/index.html.twig', 
        ['current_menu'=> 'properties',
         'properties'=> $properties,
         'form' => $form->createView()
         ]);
    }


    public function show(Property $property,string $slug): Response
    {
        if ($property->getSlug() !== $slug){
             return $this->redirectToRoute('property',
             [
                 'id' => $property->getId(),
                 'slug' => $property->getSlug()
             ], 301);
        }
        return $this->render('property/show.html.twig', ['current_menu'=> 'properties', 'property' => $property]);
    }
}

templates/property/_property.html.twig
<div class="card mb-4">
    <div class="card body" style="padding-top: 8px; padding-left: 8px;">
        <h5 class="card-title">
            <a href="/bien/{{ property.slug }}/{{ property.id}}">{{ property.title }}</a>
        </h5>
        <p class="card-text">{{ property.surface}} m² - {{property.city}} {{ property.postalCode }}</p>
        <div class="text-primary" style="font-weight:bold; font-size:2rem;">{{ property.price | number_format(0, '', ' ')}} dt</div>
    </div>
</div>

templates/property/index.html.twig
{% extends "base.html.twig" %}
{% block title "Tous nos Biens !"%}
{% block body %}
<div class="jumbotron">
    <div class="container">
        {{ form_start(form) }}
        <div class="form-row align-items-end">
            <div class="col">
                {{ form_row(form.minSurface)}}
            </div>
            <div class="col">
                {{ form_row(form.maxprice)}}
            </div>
            <div class="col">
                <div class="form-group">
                    <button class="btn btn-primary">Rechercher</button>
                </div>
            </div>
        </div>
        
        {{ form_end(form) }}
    </div>
</div>
<div class="container mt-4">
    <h1>Voir Tous nos Biens !</h1>

    <div class="row">
        {% for property in properties %}
        <div class="col-md-4">
            {%  include 'property/_property.html.twig' %}
        </div>
        {% endfor %}
    </div>

    <div class="pagination">
        {{ knp_pagination_render(properties) }}
    </div>

</div>

{% endblock %}

templates/property/show.html.twig
{% extends "base.html.twig" %}

{% block body %}
<div class="jumbotron">
    <div class="container">
        <div class="row">
            <div class="col-md-8">
    
            </div>
            <div class="col-md-4">
                <h1>{{ property.title }}</h1>
                <h2>{{ property.rooms }} piéces - {{ property.surface }} m²</h2>
                <div class="text-primary" style="font-weight:bold; font-size:4rem;">{{ property.price | number_format(0, '', ' ')}} dt</div>
                <a href="#" class="btn btn-primary">Contactez l'agence </a>
            </div>
        </div>
    </div>
</div>
<div class="container mt-4">
    <p>
        {{ property.description | nl2br }}
    </p>

    <div class="row">
        <div class="col-md-8">
            <h2>Caractéristiques</h2>
            <table class="table table-striped">
                <tr>
                    <td>Surface Habitable</td>
                    <td>{{ property.surface}} m²</td>
                </tr>
                <tr>
                    <td>Piéces</td>
                    <td>{{ property.rooms}} </td>
                </tr>
                <tr>
                    <td>Chambres</td>
                    <td>{{ property.bedrooms}}</td>
                </tr>
                <tr>
                    <td>Etage</td>
                    <td>{{ property.floor}}</td>
                </tr>
                <tr>
                    <td>Chauffage</td>
                    <td>{{ property.HeatType}}</td>
                </tr>
               
            </table>
        </div>
        <div class="col-md-4">
        <h2>Spécificités</h2>  

        </div>
    </div>
</div>
{% endblock %}